Repository SierraSoftworks/git-tool, pull requests merged in 2020-07, with the labels that each got.

#44 Make it possible to manage aliases using gt config
  src/commands/complete.rs
  src/commands/config.rs
  src/commands/info.rs
  src/commands/open.rs
  src/core/config.rs
Labels: enhancement

#53 chore: Update some dependencies
  Cargo.lock
  Cargo.toml
  src/commands/branch.rs
  src/commands/config.rs
  src/commands/new.rs
  src/commands/open.rs
  src/commands/scratch.rs
  src/tasks/create_remote.rs
  src/tasks/git_checkout.rs
  src/tasks/git_clone.rs
  src/tasks/git_init.rs
  src/tasks/git_remote.rs
  src/tasks/new_folder.rs
Labels: bug

#58 fix: Don't attempt to escape incoming command line arguments for legacy update flag
  src/main.rs
Labels: bug

#59 ci: Switch to v2 of artifact tools (which ensures that the correct Cargo file is used for release builds)
  .github/workflows/rust-release.yml
Labels: bug

#79 Don't report missing key-ring entries as a system error
  src/errors/keyring.rs
Labels: bug

#82 Add a `gt fix` command to update repo remotes when you move them
  src/commands/fix.rs
  src/commands/mod.rs
  src/git/mod.rs
  src/git/remote.rs
  src/git/remote_add.rs
  src/tasks/git_remote.rs
Labels: enhancement

#85 fix: Don't return an error when attempting to create a GitHub repo which already exists
  src/online/service/github.rs
Labels: bug

#86 fix: Use Sentry symbolicator for debug info and return to release builds
  .github/workflows/rust-release.yml
  Cargo.toml
Labels: bug

#88 refactor: Switch to Clap v3
  Cargo.lock
  Cargo.toml
  src/commands/apps.rs
  src/commands/auth.rs
  src/commands/branch.rs
  src/commands/complete.rs
  src/commands/config.rs
  src/commands/fix.rs
  src/commands/ignore.rs
  src/commands/info.rs
  src/commands/list.rs
  src/commands/mod.rs
  src/commands/new.rs
  src/commands/open.rs
  src/commands/scratch.rs
  src/commands/services.rs
  src/commands/shell_init.rs
  src/commands/update.rs
  src/main.rs
Labels: dependencies
